app: api-gateway-lambda-app
service: api-gateway-lambda
provider:
  name: aws
  runtime: python3.7
  role: "arn:aws:iam::615953452051:role/drl-link-company-lambda"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: greet
          method: get
