app: api-gateway-lambda-app
service: api-gateway-lambda
provider:
  name: aws
  runtime: python3.7
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: greet
          method: get
